name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.0'

    - name: Create .env files from secrets
      run: |
        ENV_CONTENT="DB_HOST=${{ secrets.DB_HOST }}
        DB_USER=${{ secrets.DB_USER }}
        DB_PASSWORD=${{ secrets.DB_PASSWORD }}
        DB_PORT=${{ secrets.DB_PORT }}
        DB_NAME=${{ secrets.DB_NAME }}
        SALT=akunakpacarCHINDOFineshyt
        HOST_ADDRESS=localhost
        HOST_PORT=8080
        LOG_PATH=logs
        EMAIL_VERIFICATION_DURATION=2
        OPEN_AI_API_KEY=${{ secrets.OPEN_AI_API_KEY }}
        REPLICATE_API_TOKEN=${{ secrets.REPLICATE_API_TOKEN }}"

        echo "$ENV_CONTENT" > .env
        mkdir -p test
        echo "$ENV_CONTENT" > test/.env

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
